#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinemaOtomasyonu
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Sinema")]
	public partial class DataSinemaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBiletKesim(BiletKesim instance);
    partial void UpdateBiletKesim(BiletKesim instance);
    partial void DeleteBiletKesim(BiletKesim instance);
    partial void InsertSeanslar(Seanslar instance);
    partial void UpdateSeanslar(Seanslar instance);
    partial void DeleteSeanslar(Seanslar instance);
    partial void InsertFilmler(Filmler instance);
    partial void UpdateFilmler(Filmler instance);
    partial void DeleteFilmler(Filmler instance);
    partial void InsertKullanicilar(Kullanicilar instance);
    partial void UpdateKullanicilar(Kullanicilar instance);
    partial void DeleteKullanicilar(Kullanicilar instance);
    partial void InsertPromosyon(Promosyon instance);
    partial void UpdatePromosyon(Promosyon instance);
    partial void DeletePromosyon(Promosyon instance);
    partial void InsertSalonlar(Salonlar instance);
    partial void UpdateSalonlar(Salonlar instance);
    partial void DeleteSalonlar(Salonlar instance);
    #endregion
		
		public DataSinemaDataContext() : 
				base(global::SinemaOtomasyonu.Properties.Settings.Default.SinemaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataSinemaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataSinemaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataSinemaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataSinemaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BiletKesim> BiletKesims
		{
			get
			{
				return this.GetTable<BiletKesim>();
			}
		}
		
		public System.Data.Linq.Table<Seanslar> Seanslars
		{
			get
			{
				return this.GetTable<Seanslar>();
			}
		}
		
		public System.Data.Linq.Table<Filmler> Filmlers
		{
			get
			{
				return this.GetTable<Filmler>();
			}
		}
		
		public System.Data.Linq.Table<Kullanicilar> Kullanicilars
		{
			get
			{
				return this.GetTable<Kullanicilar>();
			}
		}
		
		public System.Data.Linq.Table<Promosyon> Promosyons
		{
			get
			{
				return this.GetTable<Promosyon>();
			}
		}
		
		public System.Data.Linq.Table<Salonlar> Salonlars
		{
			get
			{
				return this.GetTable<Salonlar>();
			}
		}
		
		public System.Data.Linq.Table<vwBiletDuzenle> vwBiletDuzenles
		{
			get
			{
				return this.GetTable<vwBiletDuzenle>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BiletKesim")]
	public partial class BiletKesim : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _SeansId;
		
		private string _FilmAdi;
		
		private System.Nullable<int> _SalonNo;
		
		private string _KoltukNo;
		
		private string _BiletTipi;
		
		private System.Nullable<decimal> _Tutar;
		
		private System.Nullable<int> _PromosyonId;
		
		private EntityRef<Seanslar> _Seanslar;
		
		private EntityRef<Promosyon> _Promosyon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSeansIdChanging(System.Nullable<int> value);
    partial void OnSeansIdChanged();
    partial void OnFilmAdiChanging(string value);
    partial void OnFilmAdiChanged();
    partial void OnSalonNoChanging(System.Nullable<int> value);
    partial void OnSalonNoChanged();
    partial void OnKoltukNoChanging(string value);
    partial void OnKoltukNoChanged();
    partial void OnBiletTipiChanging(string value);
    partial void OnBiletTipiChanged();
    partial void OnTutarChanging(System.Nullable<decimal> value);
    partial void OnTutarChanged();
    partial void OnPromosyonIdChanging(System.Nullable<int> value);
    partial void OnPromosyonIdChanged();
    #endregion
		
		public BiletKesim()
		{
			this._Seanslar = default(EntityRef<Seanslar>);
			this._Promosyon = default(EntityRef<Promosyon>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeansId", DbType="Int")]
		public System.Nullable<int> SeansId
		{
			get
			{
				return this._SeansId;
			}
			set
			{
				if ((this._SeansId != value))
				{
					if (this._Seanslar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSeansIdChanging(value);
					this.SendPropertyChanging();
					this._SeansId = value;
					this.SendPropertyChanged("SeansId");
					this.OnSeansIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilmAdi", DbType="NVarChar(50)")]
		public string FilmAdi
		{
			get
			{
				return this._FilmAdi;
			}
			set
			{
				if ((this._FilmAdi != value))
				{
					this.OnFilmAdiChanging(value);
					this.SendPropertyChanging();
					this._FilmAdi = value;
					this.SendPropertyChanged("FilmAdi");
					this.OnFilmAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalonNo", DbType="Int")]
		public System.Nullable<int> SalonNo
		{
			get
			{
				return this._SalonNo;
			}
			set
			{
				if ((this._SalonNo != value))
				{
					this.OnSalonNoChanging(value);
					this.SendPropertyChanging();
					this._SalonNo = value;
					this.SendPropertyChanged("SalonNo");
					this.OnSalonNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KoltukNo", DbType="NVarChar(50)")]
		public string KoltukNo
		{
			get
			{
				return this._KoltukNo;
			}
			set
			{
				if ((this._KoltukNo != value))
				{
					this.OnKoltukNoChanging(value);
					this.SendPropertyChanging();
					this._KoltukNo = value;
					this.SendPropertyChanged("KoltukNo");
					this.OnKoltukNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BiletTipi", DbType="NVarChar(50)")]
		public string BiletTipi
		{
			get
			{
				return this._BiletTipi;
			}
			set
			{
				if ((this._BiletTipi != value))
				{
					this.OnBiletTipiChanging(value);
					this.SendPropertyChanging();
					this._BiletTipi = value;
					this.SendPropertyChanged("BiletTipi");
					this.OnBiletTipiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tutar", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> Tutar
		{
			get
			{
				return this._Tutar;
			}
			set
			{
				if ((this._Tutar != value))
				{
					this.OnTutarChanging(value);
					this.SendPropertyChanging();
					this._Tutar = value;
					this.SendPropertyChanged("Tutar");
					this.OnTutarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PromosyonId", DbType="Int")]
		public System.Nullable<int> PromosyonId
		{
			get
			{
				return this._PromosyonId;
			}
			set
			{
				if ((this._PromosyonId != value))
				{
					if (this._Promosyon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPromosyonIdChanging(value);
					this.SendPropertyChanging();
					this._PromosyonId = value;
					this.SendPropertyChanged("PromosyonId");
					this.OnPromosyonIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Seanslar_BiletKesim", Storage="_Seanslar", ThisKey="SeansId", OtherKey="Id", IsForeignKey=true, DeleteRule="CASCADE")]
		public Seanslar Seanslar
		{
			get
			{
				return this._Seanslar.Entity;
			}
			set
			{
				Seanslar previousValue = this._Seanslar.Entity;
				if (((previousValue != value) 
							|| (this._Seanslar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Seanslar.Entity = null;
						previousValue.BiletKesims.Remove(this);
					}
					this._Seanslar.Entity = value;
					if ((value != null))
					{
						value.BiletKesims.Add(this);
						this._SeansId = value.Id;
					}
					else
					{
						this._SeansId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Seanslar");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Promosyon_BiletKesim", Storage="_Promosyon", ThisKey="PromosyonId", OtherKey="Id", IsForeignKey=true, DeleteRule="CASCADE")]
		public Promosyon Promosyon
		{
			get
			{
				return this._Promosyon.Entity;
			}
			set
			{
				Promosyon previousValue = this._Promosyon.Entity;
				if (((previousValue != value) 
							|| (this._Promosyon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Promosyon.Entity = null;
						previousValue.BiletKesims.Remove(this);
					}
					this._Promosyon.Entity = value;
					if ((value != null))
					{
						value.BiletKesims.Add(this);
						this._PromosyonId = value.Id;
					}
					else
					{
						this._PromosyonId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Promosyon");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Seanslar")]
	public partial class Seanslar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _FilmId;
		
		private System.Nullable<int> _SalonId;
		
		private string _Seans;
		
		private System.Nullable<bool> _SeansDurum;
		
		private EntitySet<BiletKesim> _BiletKesims;
		
		private EntityRef<Filmler> _Filmler;
		
		private EntityRef<Salonlar> _Salonlar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFilmIdChanging(System.Nullable<int> value);
    partial void OnFilmIdChanged();
    partial void OnSalonIdChanging(System.Nullable<int> value);
    partial void OnSalonIdChanged();
    partial void OnSeansChanging(string value);
    partial void OnSeansChanged();
    partial void OnSeansDurumChanging(System.Nullable<bool> value);
    partial void OnSeansDurumChanged();
    #endregion
		
		public Seanslar()
		{
			this._BiletKesims = new EntitySet<BiletKesim>(new Action<BiletKesim>(this.attach_BiletKesims), new Action<BiletKesim>(this.detach_BiletKesims));
			this._Filmler = default(EntityRef<Filmler>);
			this._Salonlar = default(EntityRef<Salonlar>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilmId", DbType="Int")]
		public System.Nullable<int> FilmId
		{
			get
			{
				return this._FilmId;
			}
			set
			{
				if ((this._FilmId != value))
				{
					if (this._Filmler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFilmIdChanging(value);
					this.SendPropertyChanging();
					this._FilmId = value;
					this.SendPropertyChanged("FilmId");
					this.OnFilmIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalonId", DbType="Int")]
		public System.Nullable<int> SalonId
		{
			get
			{
				return this._SalonId;
			}
			set
			{
				if ((this._SalonId != value))
				{
					if (this._Salonlar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSalonIdChanging(value);
					this.SendPropertyChanging();
					this._SalonId = value;
					this.SendPropertyChanged("SalonId");
					this.OnSalonIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seans", DbType="NVarChar(50)")]
		public string Seans
		{
			get
			{
				return this._Seans;
			}
			set
			{
				if ((this._Seans != value))
				{
					this.OnSeansChanging(value);
					this.SendPropertyChanging();
					this._Seans = value;
					this.SendPropertyChanged("Seans");
					this.OnSeansChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeansDurum", DbType="Bit")]
		public System.Nullable<bool> SeansDurum
		{
			get
			{
				return this._SeansDurum;
			}
			set
			{
				if ((this._SeansDurum != value))
				{
					this.OnSeansDurumChanging(value);
					this.SendPropertyChanging();
					this._SeansDurum = value;
					this.SendPropertyChanged("SeansDurum");
					this.OnSeansDurumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Seanslar_BiletKesim", Storage="_BiletKesims", ThisKey="Id", OtherKey="SeansId")]
		public EntitySet<BiletKesim> BiletKesims
		{
			get
			{
				return this._BiletKesims;
			}
			set
			{
				this._BiletKesims.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Filmler_Seanslar", Storage="_Filmler", ThisKey="FilmId", OtherKey="Id", IsForeignKey=true, DeleteRule="CASCADE")]
		public Filmler Filmler
		{
			get
			{
				return this._Filmler.Entity;
			}
			set
			{
				Filmler previousValue = this._Filmler.Entity;
				if (((previousValue != value) 
							|| (this._Filmler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Filmler.Entity = null;
						previousValue.Seanslars.Remove(this);
					}
					this._Filmler.Entity = value;
					if ((value != null))
					{
						value.Seanslars.Add(this);
						this._FilmId = value.Id;
					}
					else
					{
						this._FilmId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Filmler");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Salonlar_Seanslar", Storage="_Salonlar", ThisKey="SalonId", OtherKey="Id", IsForeignKey=true, DeleteRule="CASCADE")]
		public Salonlar Salonlar
		{
			get
			{
				return this._Salonlar.Entity;
			}
			set
			{
				Salonlar previousValue = this._Salonlar.Entity;
				if (((previousValue != value) 
							|| (this._Salonlar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Salonlar.Entity = null;
						previousValue.Seanslars.Remove(this);
					}
					this._Salonlar.Entity = value;
					if ((value != null))
					{
						value.Seanslars.Add(this);
						this._SalonId = value.Id;
					}
					else
					{
						this._SalonId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Salonlar");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BiletKesims(BiletKesim entity)
		{
			this.SendPropertyChanging();
			entity.Seanslar = this;
		}
		
		private void detach_BiletKesims(BiletKesim entity)
		{
			this.SendPropertyChanging();
			entity.Seanslar = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Filmler")]
	public partial class Filmler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _FAdi;
		
		private string _FTuru;
		
		private string _Afis;
		
		private string _Ozet;
		
		private System.Nullable<System.TimeSpan> _Sure;
		
		private System.Nullable<System.DateTime> _VizyonT;
		
		private string _DublajT;
		
		private string _Teknoloji;
		
		private System.Nullable<int> _HamF;
		
		private EntitySet<Seanslar> _Seanslars;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFAdiChanging(string value);
    partial void OnFAdiChanged();
    partial void OnFTuruChanging(string value);
    partial void OnFTuruChanged();
    partial void OnAfisChanging(string value);
    partial void OnAfisChanged();
    partial void OnOzetChanging(string value);
    partial void OnOzetChanged();
    partial void OnSureChanging(System.Nullable<System.TimeSpan> value);
    partial void OnSureChanged();
    partial void OnVizyonTChanging(System.Nullable<System.DateTime> value);
    partial void OnVizyonTChanged();
    partial void OnDublajTChanging(string value);
    partial void OnDublajTChanged();
    partial void OnTeknolojiChanging(string value);
    partial void OnTeknolojiChanged();
    partial void OnHamFChanging(System.Nullable<int> value);
    partial void OnHamFChanged();
    #endregion
		
		public Filmler()
		{
			this._Seanslars = new EntitySet<Seanslar>(new Action<Seanslar>(this.attach_Seanslars), new Action<Seanslar>(this.detach_Seanslars));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAdi", DbType="NVarChar(100)")]
		public string FAdi
		{
			get
			{
				return this._FAdi;
			}
			set
			{
				if ((this._FAdi != value))
				{
					this.OnFAdiChanging(value);
					this.SendPropertyChanging();
					this._FAdi = value;
					this.SendPropertyChanged("FAdi");
					this.OnFAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FTuru", DbType="NVarChar(50)")]
		public string FTuru
		{
			get
			{
				return this._FTuru;
			}
			set
			{
				if ((this._FTuru != value))
				{
					this.OnFTuruChanging(value);
					this.SendPropertyChanging();
					this._FTuru = value;
					this.SendPropertyChanged("FTuru");
					this.OnFTuruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Afis", DbType="NVarChar(MAX)")]
		public string Afis
		{
			get
			{
				return this._Afis;
			}
			set
			{
				if ((this._Afis != value))
				{
					this.OnAfisChanging(value);
					this.SendPropertyChanging();
					this._Afis = value;
					this.SendPropertyChanged("Afis");
					this.OnAfisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ozet", DbType="NVarChar(MAX)")]
		public string Ozet
		{
			get
			{
				return this._Ozet;
			}
			set
			{
				if ((this._Ozet != value))
				{
					this.OnOzetChanging(value);
					this.SendPropertyChanging();
					this._Ozet = value;
					this.SendPropertyChanged("Ozet");
					this.OnOzetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sure", DbType="Time")]
		public System.Nullable<System.TimeSpan> Sure
		{
			get
			{
				return this._Sure;
			}
			set
			{
				if ((this._Sure != value))
				{
					this.OnSureChanging(value);
					this.SendPropertyChanging();
					this._Sure = value;
					this.SendPropertyChanged("Sure");
					this.OnSureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VizyonT", DbType="Date")]
		public System.Nullable<System.DateTime> VizyonT
		{
			get
			{
				return this._VizyonT;
			}
			set
			{
				if ((this._VizyonT != value))
				{
					this.OnVizyonTChanging(value);
					this.SendPropertyChanging();
					this._VizyonT = value;
					this.SendPropertyChanged("VizyonT");
					this.OnVizyonTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DublajT", DbType="NVarChar(50)")]
		public string DublajT
		{
			get
			{
				return this._DublajT;
			}
			set
			{
				if ((this._DublajT != value))
				{
					this.OnDublajTChanging(value);
					this.SendPropertyChanging();
					this._DublajT = value;
					this.SendPropertyChanged("DublajT");
					this.OnDublajTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Teknoloji", DbType="NVarChar(50)")]
		public string Teknoloji
		{
			get
			{
				return this._Teknoloji;
			}
			set
			{
				if ((this._Teknoloji != value))
				{
					this.OnTeknolojiChanging(value);
					this.SendPropertyChanging();
					this._Teknoloji = value;
					this.SendPropertyChanged("Teknoloji");
					this.OnTeknolojiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HamF", DbType="Int")]
		public System.Nullable<int> HamF
		{
			get
			{
				return this._HamF;
			}
			set
			{
				if ((this._HamF != value))
				{
					this.OnHamFChanging(value);
					this.SendPropertyChanging();
					this._HamF = value;
					this.SendPropertyChanged("HamF");
					this.OnHamFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Filmler_Seanslar", Storage="_Seanslars", ThisKey="Id", OtherKey="FilmId")]
		public EntitySet<Seanslar> Seanslars
		{
			get
			{
				return this._Seanslars;
			}
			set
			{
				this._Seanslars.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Seanslars(Seanslar entity)
		{
			this.SendPropertyChanging();
			entity.Filmler = this;
		}
		
		private void detach_Seanslars(Seanslar entity)
		{
			this.SendPropertyChanging();
			entity.Filmler = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kullanicilar")]
	public partial class Kullanicilar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _KullaniciAdi;
		
		private string _Sifre;
		
		private string _Yetki;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnKullaniciAdiChanging(string value);
    partial void OnKullaniciAdiChanged();
    partial void OnSifreChanging(string value);
    partial void OnSifreChanged();
    partial void OnYetkiChanging(string value);
    partial void OnYetkiChanged();
    #endregion
		
		public Kullanicilar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KullaniciAdi", DbType="NVarChar(100)")]
		public string KullaniciAdi
		{
			get
			{
				return this._KullaniciAdi;
			}
			set
			{
				if ((this._KullaniciAdi != value))
				{
					this.OnKullaniciAdiChanging(value);
					this.SendPropertyChanging();
					this._KullaniciAdi = value;
					this.SendPropertyChanged("KullaniciAdi");
					this.OnKullaniciAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sifre", DbType="NVarChar(50)")]
		public string Sifre
		{
			get
			{
				return this._Sifre;
			}
			set
			{
				if ((this._Sifre != value))
				{
					this.OnSifreChanging(value);
					this.SendPropertyChanging();
					this._Sifre = value;
					this.SendPropertyChanged("Sifre");
					this.OnSifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yetki", DbType="NVarChar(50)")]
		public string Yetki
		{
			get
			{
				return this._Yetki;
			}
			set
			{
				if ((this._Yetki != value))
				{
					this.OnYetkiChanging(value);
					this.SendPropertyChanging();
					this._Yetki = value;
					this.SendPropertyChanged("Yetki");
					this.OnYetkiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Promosyon")]
	public partial class Promosyon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _PromosyonAdi;
		
		private System.Nullable<int> _PTutar;
		
		private string _Aciklama;
		
		private EntitySet<BiletKesim> _BiletKesims;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnPromosyonAdiChanging(string value);
    partial void OnPromosyonAdiChanged();
    partial void OnPTutarChanging(System.Nullable<int> value);
    partial void OnPTutarChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    #endregion
		
		public Promosyon()
		{
			this._BiletKesims = new EntitySet<BiletKesim>(new Action<BiletKesim>(this.attach_BiletKesims), new Action<BiletKesim>(this.detach_BiletKesims));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PromosyonAdi", DbType="NVarChar(50)")]
		public string PromosyonAdi
		{
			get
			{
				return this._PromosyonAdi;
			}
			set
			{
				if ((this._PromosyonAdi != value))
				{
					this.OnPromosyonAdiChanging(value);
					this.SendPropertyChanging();
					this._PromosyonAdi = value;
					this.SendPropertyChanged("PromosyonAdi");
					this.OnPromosyonAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PTutar", DbType="Int")]
		public System.Nullable<int> PTutar
		{
			get
			{
				return this._PTutar;
			}
			set
			{
				if ((this._PTutar != value))
				{
					this.OnPTutarChanging(value);
					this.SendPropertyChanging();
					this._PTutar = value;
					this.SendPropertyChanged("PTutar");
					this.OnPTutarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="NVarChar(250)")]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Promosyon_BiletKesim", Storage="_BiletKesims", ThisKey="Id", OtherKey="PromosyonId")]
		public EntitySet<BiletKesim> BiletKesims
		{
			get
			{
				return this._BiletKesims;
			}
			set
			{
				this._BiletKesims.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BiletKesims(BiletKesim entity)
		{
			this.SendPropertyChanging();
			entity.Promosyon = this;
		}
		
		private void detach_BiletKesims(BiletKesim entity)
		{
			this.SendPropertyChanging();
			entity.Promosyon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Salonlar")]
	public partial class Salonlar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _SalonNo;
		
		private System.Nullable<int> _Kapasite;
		
		private string _SalonTuru;
		
		private string _KoltukTuru;
		
		private System.Nullable<int> _SiraNo;
		
		private string _ReservedKoltuk;
		
		private string _KoltukAktar;
		
		private System.Nullable<bool> _SalonDurum;
		
		private string _SeansSaat;
		
		private System.Nullable<int> _DurumBir;
		
		private System.Nullable<int> _Durumİki;
		
		private System.Nullable<int> _DurumUc;
		
		private System.Nullable<int> _DurumDort;
		
		private System.Nullable<int> _DurumBes;
		
		private EntitySet<Seanslar> _Seanslars;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSalonNoChanging(System.Nullable<int> value);
    partial void OnSalonNoChanged();
    partial void OnKapasiteChanging(System.Nullable<int> value);
    partial void OnKapasiteChanged();
    partial void OnSalonTuruChanging(string value);
    partial void OnSalonTuruChanged();
    partial void OnKoltukTuruChanging(string value);
    partial void OnKoltukTuruChanged();
    partial void OnSiraNoChanging(System.Nullable<int> value);
    partial void OnSiraNoChanged();
    partial void OnReservedKoltukChanging(string value);
    partial void OnReservedKoltukChanged();
    partial void OnKoltukAktarChanging(string value);
    partial void OnKoltukAktarChanged();
    partial void OnSalonDurumChanging(System.Nullable<bool> value);
    partial void OnSalonDurumChanged();
    partial void OnSeansSaatChanging(string value);
    partial void OnSeansSaatChanged();
    partial void OnDurumBirChanging(System.Nullable<int> value);
    partial void OnDurumBirChanged();
    partial void OnDurumİkiChanging(System.Nullable<int> value);
    partial void OnDurumİkiChanged();
    partial void OnDurumUcChanging(System.Nullable<int> value);
    partial void OnDurumUcChanged();
    partial void OnDurumDortChanging(System.Nullable<int> value);
    partial void OnDurumDortChanged();
    partial void OnDurumBesChanging(System.Nullable<int> value);
    partial void OnDurumBesChanged();
    #endregion
		
		public Salonlar()
		{
			this._Seanslars = new EntitySet<Seanslar>(new Action<Seanslar>(this.attach_Seanslars), new Action<Seanslar>(this.detach_Seanslars));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalonNo", DbType="Int")]
		public System.Nullable<int> SalonNo
		{
			get
			{
				return this._SalonNo;
			}
			set
			{
				if ((this._SalonNo != value))
				{
					this.OnSalonNoChanging(value);
					this.SendPropertyChanging();
					this._SalonNo = value;
					this.SendPropertyChanged("SalonNo");
					this.OnSalonNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kapasite", DbType="Int")]
		public System.Nullable<int> Kapasite
		{
			get
			{
				return this._Kapasite;
			}
			set
			{
				if ((this._Kapasite != value))
				{
					this.OnKapasiteChanging(value);
					this.SendPropertyChanging();
					this._Kapasite = value;
					this.SendPropertyChanged("Kapasite");
					this.OnKapasiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalonTuru", DbType="NVarChar(50)")]
		public string SalonTuru
		{
			get
			{
				return this._SalonTuru;
			}
			set
			{
				if ((this._SalonTuru != value))
				{
					this.OnSalonTuruChanging(value);
					this.SendPropertyChanging();
					this._SalonTuru = value;
					this.SendPropertyChanged("SalonTuru");
					this.OnSalonTuruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KoltukTuru", DbType="NVarChar(50)")]
		public string KoltukTuru
		{
			get
			{
				return this._KoltukTuru;
			}
			set
			{
				if ((this._KoltukTuru != value))
				{
					this.OnKoltukTuruChanging(value);
					this.SendPropertyChanging();
					this._KoltukTuru = value;
					this.SendPropertyChanged("KoltukTuru");
					this.OnKoltukTuruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiraNo", DbType="Int")]
		public System.Nullable<int> SiraNo
		{
			get
			{
				return this._SiraNo;
			}
			set
			{
				if ((this._SiraNo != value))
				{
					this.OnSiraNoChanging(value);
					this.SendPropertyChanging();
					this._SiraNo = value;
					this.SendPropertyChanged("SiraNo");
					this.OnSiraNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReservedKoltuk", DbType="NVarChar(50)")]
		public string ReservedKoltuk
		{
			get
			{
				return this._ReservedKoltuk;
			}
			set
			{
				if ((this._ReservedKoltuk != value))
				{
					this.OnReservedKoltukChanging(value);
					this.SendPropertyChanging();
					this._ReservedKoltuk = value;
					this.SendPropertyChanged("ReservedKoltuk");
					this.OnReservedKoltukChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KoltukAktar", DbType="NVarChar(50)")]
		public string KoltukAktar
		{
			get
			{
				return this._KoltukAktar;
			}
			set
			{
				if ((this._KoltukAktar != value))
				{
					this.OnKoltukAktarChanging(value);
					this.SendPropertyChanging();
					this._KoltukAktar = value;
					this.SendPropertyChanged("KoltukAktar");
					this.OnKoltukAktarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalonDurum", DbType="Bit")]
		public System.Nullable<bool> SalonDurum
		{
			get
			{
				return this._SalonDurum;
			}
			set
			{
				if ((this._SalonDurum != value))
				{
					this.OnSalonDurumChanging(value);
					this.SendPropertyChanging();
					this._SalonDurum = value;
					this.SendPropertyChanged("SalonDurum");
					this.OnSalonDurumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeansSaat", DbType="NVarChar(10)")]
		public string SeansSaat
		{
			get
			{
				return this._SeansSaat;
			}
			set
			{
				if ((this._SeansSaat != value))
				{
					this.OnSeansSaatChanging(value);
					this.SendPropertyChanging();
					this._SeansSaat = value;
					this.SendPropertyChanged("SeansSaat");
					this.OnSeansSaatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DurumBir", DbType="Int")]
		public System.Nullable<int> DurumBir
		{
			get
			{
				return this._DurumBir;
			}
			set
			{
				if ((this._DurumBir != value))
				{
					this.OnDurumBirChanging(value);
					this.SendPropertyChanging();
					this._DurumBir = value;
					this.SendPropertyChanged("DurumBir");
					this.OnDurumBirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Durumİki", DbType="Int")]
		public System.Nullable<int> Durumİki
		{
			get
			{
				return this._Durumİki;
			}
			set
			{
				if ((this._Durumİki != value))
				{
					this.OnDurumİkiChanging(value);
					this.SendPropertyChanging();
					this._Durumİki = value;
					this.SendPropertyChanged("Durumİki");
					this.OnDurumİkiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DurumUc", DbType="Int")]
		public System.Nullable<int> DurumUc
		{
			get
			{
				return this._DurumUc;
			}
			set
			{
				if ((this._DurumUc != value))
				{
					this.OnDurumUcChanging(value);
					this.SendPropertyChanging();
					this._DurumUc = value;
					this.SendPropertyChanged("DurumUc");
					this.OnDurumUcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DurumDort", DbType="Int")]
		public System.Nullable<int> DurumDort
		{
			get
			{
				return this._DurumDort;
			}
			set
			{
				if ((this._DurumDort != value))
				{
					this.OnDurumDortChanging(value);
					this.SendPropertyChanging();
					this._DurumDort = value;
					this.SendPropertyChanged("DurumDort");
					this.OnDurumDortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DurumBes", DbType="Int")]
		public System.Nullable<int> DurumBes
		{
			get
			{
				return this._DurumBes;
			}
			set
			{
				if ((this._DurumBes != value))
				{
					this.OnDurumBesChanging(value);
					this.SendPropertyChanging();
					this._DurumBes = value;
					this.SendPropertyChanged("DurumBes");
					this.OnDurumBesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Salonlar_Seanslar", Storage="_Seanslars", ThisKey="Id", OtherKey="SalonId")]
		public EntitySet<Seanslar> Seanslars
		{
			get
			{
				return this._Seanslars;
			}
			set
			{
				this._Seanslars.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Seanslars(Seanslar entity)
		{
			this.SendPropertyChanging();
			entity.Salonlar = this;
		}
		
		private void detach_Seanslars(Seanslar entity)
		{
			this.SendPropertyChanging();
			entity.Salonlar = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwBiletDuzenle")]
	public partial class vwBiletDuzenle
	{
		
		private System.Nullable<int> _Id;
		
		private System.Nullable<int> _SeansId;
		
		private string _FilmAdi;
		
		private System.Nullable<int> _SalonNo;
		
		private string _KoltukNo;
		
		private string _BiletTipi;
		
		private System.Nullable<decimal> _Tutar;
		
		private System.Nullable<int> _PromosyonId;
		
		private string _Seans;
		
		private string _FTuru;
		
		private System.Nullable<System.TimeSpan> _Sure;
		
		private string _DublajT;
		
		private string _Teknoloji;
		
		private string _PromosyonAdi;
		
		private System.Nullable<int> _PTutar;
		
		public vwBiletDuzenle()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int")]
		public System.Nullable<int> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeansId", DbType="Int")]
		public System.Nullable<int> SeansId
		{
			get
			{
				return this._SeansId;
			}
			set
			{
				if ((this._SeansId != value))
				{
					this._SeansId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilmAdi", DbType="NVarChar(50)")]
		public string FilmAdi
		{
			get
			{
				return this._FilmAdi;
			}
			set
			{
				if ((this._FilmAdi != value))
				{
					this._FilmAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalonNo", DbType="Int")]
		public System.Nullable<int> SalonNo
		{
			get
			{
				return this._SalonNo;
			}
			set
			{
				if ((this._SalonNo != value))
				{
					this._SalonNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KoltukNo", DbType="NVarChar(50)")]
		public string KoltukNo
		{
			get
			{
				return this._KoltukNo;
			}
			set
			{
				if ((this._KoltukNo != value))
				{
					this._KoltukNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BiletTipi", DbType="NVarChar(50)")]
		public string BiletTipi
		{
			get
			{
				return this._BiletTipi;
			}
			set
			{
				if ((this._BiletTipi != value))
				{
					this._BiletTipi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tutar", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> Tutar
		{
			get
			{
				return this._Tutar;
			}
			set
			{
				if ((this._Tutar != value))
				{
					this._Tutar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PromosyonId", DbType="Int")]
		public System.Nullable<int> PromosyonId
		{
			get
			{
				return this._PromosyonId;
			}
			set
			{
				if ((this._PromosyonId != value))
				{
					this._PromosyonId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seans", DbType="NVarChar(50)")]
		public string Seans
		{
			get
			{
				return this._Seans;
			}
			set
			{
				if ((this._Seans != value))
				{
					this._Seans = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FTuru", DbType="NVarChar(50)")]
		public string FTuru
		{
			get
			{
				return this._FTuru;
			}
			set
			{
				if ((this._FTuru != value))
				{
					this._FTuru = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sure", DbType="Time")]
		public System.Nullable<System.TimeSpan> Sure
		{
			get
			{
				return this._Sure;
			}
			set
			{
				if ((this._Sure != value))
				{
					this._Sure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DublajT", DbType="NVarChar(50)")]
		public string DublajT
		{
			get
			{
				return this._DublajT;
			}
			set
			{
				if ((this._DublajT != value))
				{
					this._DublajT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Teknoloji", DbType="NVarChar(50)")]
		public string Teknoloji
		{
			get
			{
				return this._Teknoloji;
			}
			set
			{
				if ((this._Teknoloji != value))
				{
					this._Teknoloji = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PromosyonAdi", DbType="NVarChar(50)")]
		public string PromosyonAdi
		{
			get
			{
				return this._PromosyonAdi;
			}
			set
			{
				if ((this._PromosyonAdi != value))
				{
					this._PromosyonAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PTutar", DbType="Int")]
		public System.Nullable<int> PTutar
		{
			get
			{
				return this._PTutar;
			}
			set
			{
				if ((this._PTutar != value))
				{
					this._PTutar = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
